[package]
name = "olytest"
version = "0.1.0"
authors = ["ilya sheprut <optozorax@gmail.com>"]
edition = "2018"

[dependencies]
termcolor = "1.1.2"
termcolor_macro = { "git" = "https://github.com/optozorax/termcolor_macro", rev = "b1d8850" }
toml = "0.5.7"
diff = "0.1.12"
anyhow = "1.0.34"
